name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  release:
    permissions:
      contents: write
    uses: Aegolius-Labs/.github/.github/workflows/conventional-release.yml@main
